KAZUTO = (
  "I'd rather die with someone than let that person die before my eyes.",
  "Levels are just numbers....",
  "Well it doesn't matter... says the Sung Jin-Woo",
  "Dojeto left TG who will help Sung??",
  "Its useless to ask for... happiness is a lie",
  "@SirAbraxas is a Simp so better watch out",
  "Durov has left the chat",
  "Durov has entered the chat",
  "Ayanokoji or Sung and the ArinX",
  "Why run for happiness when u cant have it",
  "Real pain is the result of losing someone you care about.",
  "You can go anywhere you want in this world with a single blade.",
  "It is pointless to question who someone really is... @Dojeto is a pro indeed",
  "No Matter What, My Heart Will Be Forever Yours, And I Will Fight Until The Day I See You Again.",
  "I Thought That The Closer The Real And Virtual World Got, The Better The Future Would Be. But The More The Boundary Between Them Blurs, The More It Starts To Trick People.",
  "Sung Jin Woo is a demon indeed...",
  "Dont u dare play games with me... I will call the GodlyDemon Sung and @Dojeto ...",
  "Things tend to have a great taste in life until u eat them... ",
  "My personality coincides with a lot of characters... I am leathal and dangerous... ",
  "We tend to stay happy as long as people near us dont dare hurting us...",
  "Live long and prosper... -Mr.Spock",
  "Emotions are alien to me, I am a scientist... -Mr.Spock",
  "Here if you are trying to rate me on the scale of 1 to 10 then I'm on 0 my friend you can't judge my moves. -@PirateMonkeyDlyffy",
  "It's true that being alone and lonely are two completely different things but they are one heck of a painful combination. -Yuta",
  "Win in silence , let them think you are losing -Yuta",
  "Who needs fuckin' dreams, When whole life has been a nightmare  -Dravill",
  "Where should i go 😕??? \n Should i take left where nothing is right 💜 \n Or \n Should i take right where nothing is left 🙂",
  "Human betrayed by a Human turns into a Demon.... -@SirAbraxas",
  "Better die once than dying everyday -Yuta",
  "People change with time... You can't blame a tree for shedding his leaves...cause it's natural -@SirAbraxas",
  "I want changes -@imArinX",
  "Have a taste of betrayal..."
)

GBAM = "<b>Time To Steal Girl Friend from {user2}</b>  \n \n➩Chat Id : <code>{chatid}</code> \n➩Reason : <i>{reason}</i> \n➩Number of Gf Steal : <code>{nogf}</code> \n \n<b>GFBanned By {user1}</b>"

NO_GF = (
       "1",
       "2",
       "3", 
       "4", 
       "5", 
       "6", 
       "7", 
       "8", 
       "9", 
       "10", 
) 

GFBAM_REASON = (
    "Pro af",
    "Pro BOT Owner",
    "Unpaid Herku bills",
    "Multiple telegrum id",
    "Never helps noobs",
    "pokimon trainer",
    "bullied Sung",
    "Doesnt Give Sudo",
    "Piro spy",
    "loves K-poop",
    "Grandson of lars",
    "Waifu thif",
    "spammir of tinder",
    "pro coder",
    "Doesnt love anime",
    "doesnt know the differnce between cartoon and anime",
    "peru but gey",
    "Always onlin on tg",
    "Always happi",

)


KIRI_IMG = (
  "https://i.imgur.com/SLawXBp.jpeg",
  "https://i.imgur.com/G8NjbXE.jpg",
  "https://i.imgur.com/ZpmxarX.png",
  "https://i.imgur.com/VmmaZNW.jpeg",
  "https://i.imgur.com/m1lXahZ.jpg",
  "https://i.imgur.com/kbv3d6k.png",
  "https://i.imgur.com/kz1eVpu.jpg",
  "https://i.imgur.com/B5IFeRd.jpeg",
  "https://i.imgur.com/weFRPTk.jpg",
  "https://i.imgur.com/AqxPYun.jpeg",
)
