KAZUTO = (
  "I'd rather die with someone than let that person die before my eyes.",
  "Levels are just numbers....",
  "Well it doesn't matter... says the Sung Jin-Woo",
  "Dojeto left TG who will help Sung??",
  "Its useless to ask for... happiness is a lie",
  "@SirAbraxas is a Simp so better watch out",
  "Durov has left the chat",
  "Durov has entered the chat",
  "Ayanokoji or Sung and the ArinX",
  "Why run for happiness when u cant have it",
  "Real pain is the result of losing someone you care about.",
  "You can go anywhere you want in this world with a single blade.",
  "It is pointless to question who someone really is... @Dojeto is a pro indeed",
  "No Matter What, My Heart Will Be Forever Yours, And I Will Fight Until The Day I See You Again.",
  "I Thought That The Closer The Real And Virtual World Got, The Better The Future Would Be. But The More The Boundary Between Them Blurs, The More It Starts To Trick People.",
  "Sung Jin Woo is a demon indeed...",
  "Dont u dare play games with me... I will call the GodlyDemon Sung and @Dojeto ...",
)

KIRI_IMG = (
  "https://i.imgur.com/SLawXBp.jpeg",
  "https://i.imgur.com/G8NjbXE.jpg",
  "https://i.imgur.com/ZpmxarX.png",
  "https://i.imgur.com/VmmaZNW.jpeg",
  "https://i.imgur.com/m1lXahZ.jpg",
  "https://i.imgur.com/kbv3d6k.png",
  "https://i.imgur.com/kz1eVpu.jpg",
  "https://i.imgur.com/B5IFeRd.jpeg",
  "https://i.imgur.com/weFRPTk.jpg",
  "https://i.imgur.com/AqxPYun.jpeg",
)
